name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to AWS EC2
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        ssh-keyscan ec2-18-181-77-247.ap-northeast-1.compute.amazonaws.com >> ~/.ssh/known_hosts

    - name: SSH and Deploy
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@ec2-18-181-77-247.ap-northeast-1.compute.amazonaws.com << EOF
          sudo usermod -aG docker ubuntu
          git clone https://github.com/mahesh-jackett/actions.git
          cd actions
          newgrp docker && docker build -t your-app . && docker run -d -p 8000:8000 your-app
        EOF
